#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".



#
# Auto-generate translated StartDSTwithParams using sed and predefined sed's rules
#
#
fname_eng="DSTcmdLauncherEng.cmd"
fname_rus="DSTcmdLauncherRus.cmd"
CHANGED=$(git diff --name-only --cached --diff-filter=ACMR | grep -c -F "${fname_rus}")
if  [ "$CHANGED" -ne "0" ]; then
    if [ -f StartDSTwithParamsEng.cmd ]; then
        date_eng=$(date -r ${fname_eng} +%s)
        date_rus=$(date -r ${fname_rus} +%s)
        echo -n "'${fname_eng}' date/time modification: "
        date -r ${fname_eng} +"%F  %X"
        echo -n "'${fname_rus}' date/time modification: "
        date -r ${fname_rus} +"%F  %X"
        if [ "$date_eng" -gt "$date_rus" ]; then
            echo -e "\nTime of last modification ${fname_eng} greater than ${fname_rus}.\n"
            echo "Commit aborted."
            exit 3
        fi
    fi
    sed -b -f translate/rus2eng.sed ${fname_rus} > ${fname_eng};
    git add $fname_eng;
fi
