#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".



#
# Auto-generate translated StartDSTwithParams using sed and predefined sed's rules
#
#
CHANGED=$(git diff --name-only --cached --diff-filter=ACMR | grep -c "StartDSTwithParamsRus.cmd")
if  [ "$CHANGED" -ne "0" ]; then
    if [ -f StartDSTwithParamsEng.cmd ]; then
        date_eng=$(stat -c "%Y" StartDSTwithParamsEng.cmd)
        date_rus=$(stat -c "%Y" StartDSTwithParamsRus.cmd)
        echo "date_eng: $date_eng\ndate_rus: $date_rus"
        if [ "$date_eng" -gt "$date_rus" ]; then
            echo "Time of last modification StartDSTwithParamsEng greater than StartDSTwithParamsRus."
            exit 1
        fi
    else
        echo "StartDSTwithParamsEng.cmd not found"
    fi
    sed -b -f translate/rus2en.sed StartDSTwithParamsRus.cmd > StartDSTwithParamsEng.cmd;
    git add StartDSTwithParamsEng.cmd;
else
    echo "StartDSTwithParamsRus.cmd not changed"
fi