#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".





#
# Auto-generate translated script using sed and predefined sed's rules
#
#
CHANGED=$(git diff --name-only --cached --diff-filter=ACMR | grep -c "StartDSTwithParams.cmd")
if  [ "$CHANGED" != "0" ]; then
    sed -b -f translate/rus2en.sed StartDSTwithParams.cmd > StartDSTwithParamsEng.cmd
    git add StartDSTwithParamsEng.cmd
fi
